---
# MinIO server (external)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-minio
  namespace: social
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: kube-system
      sectionName: https
  hostnames:
    - mfile.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mastodon-minio
          port: 9000
---
# MinIO console (internal)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-minio-console
  namespace: social
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal-gateway
      namespace: kube-system
      sectionName: https
  hostnames:
    - mmc.k.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mastodon-minio-console
          port: 9001
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: mastodon-minio-console-auth
  namespace: social
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: mastodon-minio-console
  extAuth:
    http:
      backendRefs:
        - name: authelia
          namespace: kube-system
          port: 80
      path: /api/authz/auth-request
      headersToExtAuth:
        - Host
        - Path
        - X-Forwarded-For
        - X-Forwarded-Proto
        - X-Forwarded-Host
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
      timeout: 3s
